[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "=0.2.0-alpha.1" }
snafu = "0.4.4"
futures-preview = { version = "=0.3.0-alpha.17", features = ["async-await", "nightly"] }
log = "0.4.8"
tokio-signal = "=0.3.0-alpha.1"
env_logger = "0.6.2"
structopt = "0.2.18"
walkdir = "2.2.9"
serde = { version = "1.0.98", features = ["derive"] }
rand = "0.7.0"
derive_more = "0.15.0"
phf = { version = "0.7", features = ["macros"] }
serde_json = "1.0.40"
strum = "0.15.0"
strum_macros = "0.15.0"
bincode = "1.1.4"
bytes = ""
