[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "=0.2.0-alpha.4", default-features = false, features = ["rt-full", "signal"] }
tokio-net = { version = "=0.2.0-alpha.4", default-features = false, features = ["signal"] }
snafu = { version = "0.5.0", default-features = false, features = ["rust_1_30"] }
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
log = "0.4.8"
env_logger = { version = "0.6.2", default-features = false, features = ["termcolor", "atty", "humantime"] }
structopt = "0.3.1"
walkdir = "2.2.9"
serde = { version = "1.0.100", features = ["derive"] }
rand = "0.7.0"
phf = { version = "0.7", features = ["macros"] }
serde_json = "1.0.40"
strum = "0.15.0"
strum_macros = "0.15.0"
bytes = ""
humantime-serde = "0.1.1"
slotmap = { version = "0.4.0", features = ["unstable"] }
bitflags = "1.1.0"

[dependencies.oneshot-reqrep]
git = "https://github.com/foldu/oneshot-reqrep"
rev = "bd4f1dce63432ee6f6e525b92a1b2c16a3a653a0"

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "a7373582f2ea6381cbdaffdb4cf1163478e5d17b"
default-features = false
features = ["yaml", "expandpath"]
