[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.11", features = ["rt-core", "signal", "sync", "time", "blocking", "stream", "fs", "macros"] }
snafu = { git = "https://github.com/shepmaster/snafu", rev = "1aa2f5dd93694503b990308e48e00dc67ea2770d"}
futures-util = "0.3.1"
structopt = "0.3.9"
walkdir = "2.3.1"
serde = { version = "1.0.104", features = ["derive"] }
rand = "0.7.3"
phf = { version = "0.8.0", features = ["macros"] }
serde_json = "1.0.45"
strum = "0.17.1"
strum_macros = "0.17.1"
bytes = "0.5.4"
humantime-serde = "1.0.0"
slotmap = "0.4.0"
bitflags = "1.2.1"
serde_yaml = "0.8.11"
rusqlite = "0.21.0"
tgcd = { path = "../tgcd/tgcd", default-features = false }
refinery = { features = ["rusqlite"], version = "0.2.0" }
directories = "2.0.2"
inotify = "0.8.2"
once_cell = "1.3.1"
crossbeam-channel = "0.4.0"
chrono = "0.4.10"
log = "0.4.8"
slog = "2.5.2"
slog-term = "2.5.0"
slog-stdlog = "4.0.0"
slog-scope = "4.3.0"
refinery-migrations = "0.2.0"

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "6cafcff155e0c760d046e73c8982c003b2615043"
default-features = false
features = ["yaml", "expandpath"]

[dependencies.oneshot-reqrep]
git = "https://github.com/foldu/oneshot-reqrep"
rev = "f0bd99a0db487823ce5334037520a1472bb869c0"
