[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.6", features = ["rt-core", "signal", "sync", "time", "blocking", "stream", "fs"] }
snafu = "0.6.0"
futures-util = "0.3.1"
log = "0.4.8"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
structopt = "0.3.5"
walkdir = "2.2.9"
serde = { version = "1.0.104", features = ["derive"] }
rand = "0.7.2"
phf = { version = "0.8.0", features = ["macros"] }
serde_json = "1.0.44"
strum = "0.16.0"
strum_macros = "0.16.0"
bytes = "0.5.2"
humantime-serde = "0.1.1"
slotmap = "0.4.0"
bitflags = "1.2.1"
serde_yaml = "0.8.11"
inotify = "0.8.0"
once_cell = "1.2.0"
directories = "2.0.2"

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "6cafcff155e0c760d046e73c8982c003b2615043"
default-features = false
features = ["yaml", "expandpath"]

[dependencies.oneshot-reqrep]
git = "https://github.com/foldu/oneshot-reqrep"
rev = "f0bd99a0db487823ce5334037520a1472bb869c0"
