[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.18", features = ["rt-core", "signal", "sync", "time", "blocking", "stream", "fs", "macros"] }
snafu = "0.6.6"
futures-util = "0.3.4"
serde = { version = "1.0.106", features = ["derive"] }
phf = { version = "0.8.0", features = ["macros"] }
humantime-serde = "1.0.0"
tgcd = { git = "https://github.com/foldu/tgcd", rev = "267f03adb3b39031f0c02ce7920228189004591b", default-features = false }
directories = "2.0.2"
inotify = "0.8.2"
once_cell = "1.3.1"
log = "0.4.8"
slog = "2.5.2"
slog-term = "2.5.0"
slog-stdlog = "4.0.0"
slog-scope = "4.3.0"
tokio-i3ipc = "0.6.0"
structopt = "0.3.13"
anyhow = "1.0.28"
nix = "0.17.0"
libc = "0.2.68"
walkdir = "2.3.1"
rayon = "1.3.0"
sqlx = { rev = "a034df87c446ce1993b6dd7602333cd1a4d60894", git = "https://github.com/launchbadge/sqlx", default-features = false, features = ["sqlite", "macros", "runtime-tokio"] }
tarpc = { version = "0.20.0", features = ["tokio1", "serde-transport", "serde1"] }
tokio-serde = { version = "0.6.1", default-features = false, features = ["json"] }
pin-project = "0.4.8"
async-trait = "0.1.30"
toml = "0.5.6"
time = "0.2.15"
serde_json = "1.0.51"

[build-dependencies]
serde = "1.0.106"
structopt = "0.3.13"
