[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.0-alpha.6", default-features = false, features = ["rt-full", "signal"] }
tokio-net = { version = "0.2.0-alpha.6", default-features = false, features = ["signal"] }
snafu = { version = "0.5.0", default-features = false, features = ["rust_1_30"] }
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
log = "0.4.8"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty", "humantime"] }
structopt = "0.3.4"
walkdir = "2.2.9"
serde = { version = "1.0.102", features = ["derive"] }
rand = "0.7.2"
phf = { version = "0.8.0", features = ["macros"] }
serde_json = "1.0.41"
strum = "0.16.0"
strum_macros = "0.16.0"
bytes = "0.4.12"
humantime-serde = "0.1.1"
slotmap = { version = "0.4.0", features = ["unstable"] }
bitflags = "1.2.1"
serde_yaml = "0.8.11"

[dependencies.oneshot-reqrep]
git = "https://github.com/foldu/oneshot-reqrep"
rev = "1b5dc91e2f1a982aba3d0afab9d3f8cc29137f67"

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "a7373582f2ea6381cbdaffdb4cf1163478e5d17b"
default-features = false
features = ["yaml", "expandpath"]
