[package]
name = "pickwp"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.11", features = ["rt-core", "signal", "sync", "time", "blocking", "stream", "fs", "macros"] }
snafu = "0.6.2"
futures-util = "0.3.1"
structopt = "0.3.9"
walkdir = "2.3.1"
serde = { version = "1.0.104", features = ["derive"] }
rand = "0.7.3"
phf = { version = "0.8.0", features = ["macros"] }
serde_json = "1.0.45"
strum = "0.17.1"
strum_macros = "0.17.1"
bytes = "0.5.4"
humantime-serde = "1.0.0"
slotmap = "0.4.0"
serde_yaml = "0.8.11"
rusqlite = "0.22.0"
tgcd = { git = "https://github.com/foldu/tgcd", rev = "267f03adb3b39031f0c02ce7920228189004591b", default-features = false }
refinery = { features = ["rusqlite"], version = "0.2.0" }
directories = "2.0.2"
inotify = "0.8.2"
once_cell = "1.3.1"
crossbeam-channel = "0.4.0"
chrono = "0.4.10"
log = "0.4.8"
slog = "2.5.2"
slog-term = "2.5.0"
slog-stdlog = "4.0.0"
slog-scope = "4.3.0"
refinery-migrations = "0.2.0"
tokio-i3ipc = "0.6.0"
async-trait = "0.1.24"

[dependencies.cfgen]
git = "https://github.com/foldu/cfgen"
rev = "eccf05b15e0e25503b59b6a6ab0bf7483727bd6c"
default-features = false
features = ["yaml"]

[dependencies.oneshot-reqrep]
git = "https://github.com/foldu/oneshot-reqrep"
rev = "f0bd99a0db487823ce5334037520a1472bb869c0"

[build-dependencies]
serde = "1.0.104"
structopt = "0.3.9"
