---
wp-dir: "~/Pictures"
mode: fill
rescan-interval: 600
refresh-interval: 300
filters:
  - type: last-shown
  - type: file-time
    time-kind: mtime
    from: 2019-08-20 00:00:00
    to: 2019-09-13 00:00:00
  - type: filename
    contains: test
